--liquibase formatted sql

--changeset aleos:1
CREATE TABLE USERS
(
    id        INT          NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname VARCHAR(100) NOT NULL,
    lastname  VARCHAR(100) NOT NULL,
    email     VARCHAR(100) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    role      VARCHAR(30)  NOT NULL,
    active    BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT uq_users_email UNIQUE (email)
);

--changeset aleos:2
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE VERIFICATION_TOKEN
(
    id          UUID         NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     INT          NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    verified_at TIMESTAMP(6),

    CONSTRAINT fk_verification_table_user_id FOREIGN KEY (user_id) REFERENCES USERS ON DELETE CASCADE
)